// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc4SwmMCcglIzBcxW4jKnJvMEE48TsaYY',
    appId: '1:530530213788:web:8a24cf418e18691a92f259',
    messagingSenderId: '530530213788',
    projectId: 'brain-mri-2202',
    authDomain: 'brain-mri-2202.firebaseapp.com',
    storageBucket: 'brain-mri-2202.appspot.com',
    measurementId: 'G-DCB6J9BT9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFX_WJbpaTev6nNdg0PgIokShlILHh-kc',
    appId: '1:530530213788:android:2d15f21c0bb845e092f259',
    messagingSenderId: '530530213788',
    projectId: 'brain-mri-2202',
    storageBucket: 'brain-mri-2202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK_e84EZg0DuG3lItKlQldPZFmpvme34o',
    appId: '1:530530213788:ios:2017276d22e1b80392f259',
    messagingSenderId: '530530213788',
    projectId: 'brain-mri-2202',
    storageBucket: 'brain-mri-2202.appspot.com',
    iosBundleId: 'com.example.brainmri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK_e84EZg0DuG3lItKlQldPZFmpvme34o',
    appId: '1:530530213788:ios:986e20049183b87592f259',
    messagingSenderId: '530530213788',
    projectId: 'brain-mri-2202',
    storageBucket: 'brain-mri-2202.appspot.com',
    iosBundleId: 'com.example.brainmri.RunnerTests',
  );
}
